package org.billy.resortmanagementsystem.domain;

import jakarta.persistence.*;
import lombok.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Product {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@NotNull
	private String name;
	private String description;
	private String excerpt;

	@Enumerated(EnumType.STRING)
	private ProductType type;

	private double price;
	private int maxCap;

	@Embedded
	private AuditData auditData = new AuditData();

	// i need a constructor without id since id is auto generated by the db
	public Product(String name, String description, String excerpt, ProductType type, double price) {
		this.name = name;
		this.description = description;
		this.price = price;
		this.excerpt = excerpt;
		this.type = type;
	}
}
